# Site Settings
title: Cremazer's Github Blog
email: cremazer@gmail.com
description: This blog is a blog about the development of Cremazer.
baseurl:
url: "https://cremazer.github.io/" # the base hostname & protocol for your site
google_analytics: "UA-42914037-3"

# User Settings
username: Cremazer
user_description: South Korea. Web developer.(from 2009)
disqus_username: kyuseoshim

# Social Media
# Remove the item if you don't need it
github_username: cremazer
facebook_username: cremazer
twitter_username: cremazer
instagram_username: kyuseoshim
linkedin_username: cremazer
medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

disqus-shortname: kyuseoshim

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
